### ISSUE TITLE
SCD namespace URI

### ISSUE THREAD

**Issue by philbarker** [stuartasutton/P1484.20.3#4]
`        "scd": "https://opensource.ieee.org/rcd/v2021.json#",`
Is the namespace URI really going to have .json in it? 

I see the ttl has `@prefix scd: <https://opensource.ieee.org/scd#>` which makes more sense to me if the vocab definitions are going to be represented in multiple serializations.

**Comment by stuartasutton** [comment]
No, that is very old. The namespace actually is `https://opensource.ieee.org/scd/`

**Comment by philbarker** [comment]
OK I fixed that in the pull request.
